learning/Models/Master.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace learning.Models
{
    public class Master
    {

    }
    public class Student
    {
        public int SId { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Addr { get; set; }
        public string Mob { get; set; }
        public string Photo { get; set; }
        public string PhotoPath { get; set; }
        public string SignaturePath { get; set; }
        public string flag { get; set; }
        public string msg { get; set; }
        public List<Student> list { get; set; }
  
        
    }

    public class state
    {
        public int Value { get; set; }
        public String Text { get; set; }
        public List <state> lst { get; set; }
    }

    public class MultipleFileUploading
    {
        public string File { get; set; }
        public string FilePath { get; set; }
        public string Title { get; set; }
        public List<MultipleFileUploading> List { get; set; }
    }
}

learning/Controllers/MasterController.cs
using HRPayroll.Models;
using learning.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace learning.Controllers
{
    public class MasterController : Controller
    {
        // GET: Master
        Repos Repo = new Repos();
        Common com = new Common();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Student()
        {
            ViewBag.state = Repo.BindState();
            return View();
        }
        [HttpPost]
        public ActionResult Student(Student model)
        {
            ViewBag.state = Repo.BindState();
            Student _iresult = new Student();
            if (model.SId > 0)
            {
              
            }
            else
            {

                _iresult = Repo.InsertStudent(model);

            }
            if (Convert.ToInt32(_iresult.flag) == 1)
            {
                TempData["msg"] = _iresult.msg;
                TempData["code"] = "1";
            }
            else
            {
                TempData["msg"] = _iresult.msg;
                TempData["code"] = "0";
            }
            return View();
        }

        public JsonResult BindCity(string stateId)
        {
            var res = Repo.BindCity(Convert.ToInt32(stateId));
            return Json(res, JsonRequestBehavior.AllowGet);

        }

        public JsonResult UploadFileForRegistration(HttpPostedFileBase File)
        {
            string Dirpath = "~/Content/writereaddata/StudentRegistration/";
            string path = "";
            string filename = File.FileName;
            bool res = false;
            string msg = "";
            if (!Directory.Exists(Server.MapPath(Dirpath)))
            {
                Directory.CreateDirectory(Server.MapPath(Dirpath));
            }
            string ext = Path.GetExtension(File.FileName);
            var status = com.ValidateImagePDF_FileExtWithSize(File, 2048);
            if (status == "Valid")
            {

                filename = DateTime.Now.ToString("yyyyMMddHHmmssffff") + "_" + filename;
                string completepath = Path.Combine(Server.MapPath(Dirpath), filename);
                if (System.IO.File.Exists(completepath))
                {
                    System.IO.File.Delete(completepath);
                }

                File.SaveAs(completepath);
                path = Dirpath + filename;
                res = true;
            }
            else
            {
                msg = status;
            }
            return Json(new { result = res, fpath = path, mesg = msg });
        }

        public ActionResult Studentlist()
        {
            Student obj = new Student();
             obj.list = Repo.Studentlst();
            return View(obj);
        }

        public ActionResult Album()
        {
            return View();
        }
    }
}

learning/Views/Master/Album.cshtml
@model learning.Models.MultipleFileUploading
@{
    ViewBag.Title = "Album";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Album</h2>

<div class="row page-titles">
    <div class="ptitle">
        <h4 class="mb-1 mt-0">Add Product</h4>
        <nav aria-label="breadcrumb" class="float-left">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#-">Master</a></li>
                <li class="breadcrumb-item active" aria-current="page">Product List</li>
            </ol>
        </nav>
    </div>
    @*<div class="psearch">

        </div>*@
    <div class="pbutton">
        <div class="right text-right">

            <a href="/Admin/AddProduct" class="btn btn-success">Add Product</a>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div id="no-more-tables">
        <div class="row">
            @{
                string flag = (string)TempData["code"];
                string msg = (string)TempData["msg"];
                if (flag == "1")
                {
                    <strong>@msg</strong>
                }
                else
                {<strong>@msg</strong>

            }
            }
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        @using (Html.BeginForm("Student", "Master", FormMethod.Post))
                        {
                            <div class="row" id="Repeat">
                                <div class="col-md-6">
                                    <div class="form-group label-floating is-empty">
                                        <label class="form-control-placeholder" for="ddlProductType">Title</label>
                                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group label-floating is-empty">
                                        <label class="form-control-placeholder" for="ddlProductType">File </label>
                                        <input type="File" id="File" />
                                        @Html.HiddenFor(m => m.FilePath)
                                        <img src="" id="Fileppp" height="100px" width="100px" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating is-empty" style="margin-top:20px; text-align:right;">

                                        <input type="button" onclick="Add()" class="btn btn-success" value="Add" />
                                    </div>
                                </div>

                                <div class="col-md-6"></div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating is-empty" style="margin-top:20px; text-align:right;">
                                        <input type="submit" class="btn btn-success" value="Submit" />
                                    </div>
                                </div>




                            </div>
                        }
                    </div>


                    <input type="button" onclick="remove()" class="btn btn-success" value="remove" />
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    function Add() {
        debugger;
        var input = '<div class="col-md-6"><div class="form-group label-floating is-empty"><label class="form-control-placeholder"for= "ddlProductType"> File </label ><input type="File" id="File" /><input type="hidden" id="FilePath"><img src="" id="Fileppp" height="100px" width="100px"/></div></div>';
        $('#Repeat').append(input);
    }

    function remove() {
        $('#Repeat').children().last().remove();
    }
            function Fileupload(obj) {
        debugger;
        var filename = $(obj)[0].files[0].name;
        var fileId = $(obj).attr("id");
        var ext = obj.value.match(/\.(.+)$/)[1];

        switch (ext) {
            case 'pdf':
            case 'jpg':
            case 'jpeg':
                var fileSize = ($("#" + fileId)[0].files[0].size / 1024 / 1024);
                if (fileSize > 2) {
                    swal("", "File size should not exceed 2 MB.\r\nफाइल का साइज़ 2 MB से अधिक नहीं होना चाहिए।", "warning");
                    return false;
                }
                else {
                    var data = new FormData();
                    var files = $("#" + fileId).get(0).files;
                    if (files.length > 0) {
                        data.append("File", files[0]);
                    }
                    $("#divLoader").show();
                    $.ajax({
                        url: '@Url.Action("UploadFileForRegistration", "Master")',
                        type: "POST",
                        processData: false,
                        contentType: false,
                        data: data,
                        success: function (response) {
                            $("#divLoader").hide();

                            if (response != null) {
                                if (response.result) {
                                    $("#fileName" + fileId).text(filename);
                                    $("#" + fileId + "Path").val(response.fpath);

                                    var Url = response.fpath.replace('~/', '');
                                    $("#" + fileId + "Anchor").empty();
                                    $("#" + fileId + "Anchor").attr('href', Url);
                                    $("#" + fileId + "Anchor").show();
                                   // $("#" + fileId+"ppp").val(response.fpath.replace("~",""));
                                    $("#" + fileId+"ppp").attr("src",response.fpath.replace("~",""));
                                    $("#" + fileId + "Anchor").append('<a href="' + '@Url.Content("~/")' + Url + '" target="_blank" class="btn btn-warning anchor"><i class="fa fa-download"></i></a>');

                                    swal("", "File upload successfully. ", "success")
                                }
                                else {
                                    swal("", response.mesg, "error")
                                }
                            }
                            else {
                                swal("", "Fail to Upload File", "error")
                            }
                            return false;

                        },
                        error: function (e) {

                            $("#divLoader").hide();
                            swal("", "An Error Occured while uploading file", "error");
                        }
                    });

                }
                break;
            default:
                swal("", 'File should be in PDF/JPG/JPEG format./फाइल PDF/JPG/JPEG प्रारूप में होनी चाहिए।', "warning");
                this.value = '';
                return false;
        }

    }
</script>

learning/Views/Master/Student.cshtml
@model learning.Models.Student
@{
    ViewBag.Title = "Student";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row page-titles">
    <div class="ptitle">
        <h4 class="mb-1 mt-0">Add Product</h4>
        <nav aria-label="breadcrumb" class="float-left">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#-">Master</a></li>
                <li class="breadcrumb-item active" aria-current="page">Product List</li>
            </ol>
        </nav>
    </div>
    @*<div class="psearch">

        </div>*@
    <div class="pbutton">
        <div class="right text-right">

            <a href="/Admin/AddProduct" class="btn btn-success">Add Product</a>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div id="no-more-tables">
        <div class="row">
            @{ 
                string flag = (string)TempData["code"];
                string msg= (string)TempData["msg"];
            if (flag == "1")
            {
                        <strong>@msg</strong>
            }
            else
            {<strong>@msg</strong>

            }
            }
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        @using (Html.BeginForm("Student", "Master", FormMethod.Post))
                        {
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty">
                                    <label class="form-control-placeholder" for="ddlProductType">Student Name </label>
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty">
                                    <label class="form-control-placeholder" for="ddlProductType">Father Name </label>
                                    @Html.TextBoxFor(m => m.FName, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty">
                                    <label class="form-control-placeholder" for="ddlProductType">Mother Name </label>
                                    @Html.TextBoxFor(m => m.MName, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty">
                                    <label class="form-control-placeholder" for="ddlProductType">Select State </label>
                                    @Html.DropDownListFor(m => m.State, new SelectList(ViewBag.state, "Value", "Text"), "select", new { @class = "form-control", @onchange = "bindcity()" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty">
                                    <label class="form-control-placeholder" for="ddlProductType">Select City </label>
                                    @Html.DropDownListFor(m => m.City, new SelectList(String.Empty, "Value", "Text"), "select", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty">
                                    <label class="form-control-placeholder" for="ddlProductType">Address </label>
                                    @Html.TextBoxFor(m => m.Addr, new { @class = "form-control" })
                                </div>
                            </div> <
                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty">
                                    <label class="form-control-placeholder" for="ddlProductType">Mob </label>
                                    @Html.TextBoxFor(m => m.Mob, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty">
                                    <label class="form-control-placeholder" for="ddlProductType">Address </label>
                                    <input type="file" id="Photo" name="Photo" onchange="Fileupload(this)" />
                                    @Html.HiddenFor(m => m.PhotoPath)
                                    <img src="" height="100px" width="100px" id="Photoppp" />
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty">
                                    <label class="form-control-placeholder" for="ddlProductType">Sig </label>
                                    <input type="file" id="Signature" name="Signature" onchange="Fileupload(this)" />
                                    @Html.HiddenFor(m => m.SignaturePath)
                                  
                                    <img src="" height="100px" width="100px" id="Signatureppp" />
                                </div>
                            </div>




                            <div class="col-md-6"></div>
                            <div class="col-md-6">
                                <div class="form-group label-floating is-empty" style="margin-top:20px; text-align:right;">

                                    <input type="submit" class="btn btn-success" value="Submit" />


                                </div>
                            </div>





                        </div>
                        }
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

<script>

    function bindcity() {
        debugger;
        var stateId = $('#State').val();
        if (stateId > 0) {
            $.ajax({
                type: 'Post',
                url: '@Url.Action("BindCity","Master")',
                data: { stateId: stateId },
                dataType: 'json',
                success: function (data) {
                    if (data != null) {
                        $('#City').empty();

                        $('#City').append('<option value="">select</option>')
                        for (var i = 0; i < data.length; i++) {
                            $('#City').append('<option value=' + data[i].Value + '>' + data[i].Text + '</option>')
                        }
                    }
                    else {
                        $('#City').empty();
                    }
                }

            })
        }
        else {
            $('#City').empty();

            $('#City').append('<option value="">select</option>')
        }
    }
    function Fileupload(obj) {
        debugger;
        var filename = $(obj)[0].files[0].name;
        var fileId = $(obj).attr("id");
        var ext = obj.value.match(/\.(.+)$/)[1];

        switch (ext) {
            case 'pdf':
            case 'jpg':
            case 'jpeg':
                var fileSize = ($("#" + fileId)[0].files[0].size / 1024 / 1024);
                if (fileSize > 2) {
                    swal("", "File size should not exceed 2 MB.\r\nफाइल का साइज़ 2 MB से अधिक नहीं होना चाहिए।", "warning");
                    return false;
                }
                else {
                    var data = new FormData();
                    var files = $("#" + fileId).get(0).files;
                    if (files.length > 0) {
                        data.append("File", files[0]);
                    }
                    $("#divLoader").show();
                    $.ajax({
                        url: '@Url.Action("UploadFileForRegistration", "Master")',
                        type: "POST",
                        processData: false,
                        contentType: false,
                        data: data,
                        success: function (response) {
                            $("#divLoader").hide();

                            if (response != null) {
                                if (response.result) {
                                    $("#fileName" + fileId).text(filename);
                                    $("#" + fileId + "Path").val(response.fpath);
                           
                                    var Url = response.fpath.replace('~/', '');
                                    $("#" + fileId + "Anchor").empty();
                                    $("#" + fileId + "Anchor").attr('href', Url);
                                    $("#" + fileId + "Anchor").show();
                                   // $("#" + fileId+"ppp").val(response.fpath.replace("~",""));
                                    $("#" + fileId+"ppp").attr("src",response.fpath.replace("~",""));
                                    $("#" + fileId + "Anchor").append('<a href="' + '@Url.Content("~/")' + Url + '" target="_blank" class="btn btn-warning anchor"><i class="fa fa-download"></i></a>');

                                    swal("", "File upload successfully. ", "success")
                                }
                                else {
                                    swal("", response.mesg, "error")
                                }
                            }
                            else {
                                swal("", "Fail to Upload File", "error")
                            }
                            return false;

                        },
                        error: function (e) {

                            $("#divLoader").hide();
                            swal("", "An Error Occured while uploading file", "error");
                        }
                    });

                }
                break;
            default:
                swal("", 'File should be in PDF/JPG/JPEG format./फाइल PDF/JPG/JPEG प्रारूप में होनी चाहिए।', "warning");
                this.value = '';
                return false;
        }

    }
</script>

learning/Views/Master/Studentlist.cshtml
@model learning.Models.Student
@{
    ViewBag.Title = "Studentlist";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Studentlist</h2>



<div class="row page-titles">
    <div class="ptitle">
        <h4 class="mb-1 mt-0">Student List</h4>
        <nav aria-label="breadcrumb" class="float-left">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#-">Master</a></li>
                <li class="breadcrumb-item active" aria-current="page">Product List</li>
            </ol>
        </nav>
    </div>
    @*<div class="psearch">

        </div>*@
    <div class="pbutton">
        <div class="right text-right">

            <a href="/Admin/" class="btn btn-success">Add Product</a>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div id="no-more-tables">
        <div class="row">
            @{
                string flag = (String)TempData["code"];
                string msg = (string)TempData["msg"];
                if (flag == "1")
                {
                    <strong>@msg</strong>
                }
                else
                {<strong>@msg</strong>

            }


            }
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table">
                            <table class="table">
                                <tr>
                                    <th>Sr.No</th>
                                    <th>Name</th>
                                    <th>Father Name</th>
                                    <th> Mother Name</th>
                                    <th>City</th>
                                    <th>State</th>
                                    <th>Mobile</th>

                                    <th>Photo</th>
                                    <th>Signature</th>
                                    <th></th>
                                </tr>

                                @if (Model.list != null)
                                {
                                    int i = 0;
                                    foreach (var item in Model.list)
                                    {
                                        i++;
                                        <tr>
                                            <td>@(i)</td>
                                            <td>@item.Name</td>
                                            <td>@item.FName</td>
                                            <td>@item.MName</td>
                                            <td>@item.City</td>
                                            <td>@item.State</td>
                                            <td>@item.Mob</td>
                                            @if (!String.IsNullOrEmpty(item.Photo))
                                            {
                                                <td><img src="@item.Photo.Replace("~","")" height="100px" width="100px" /></td>
                                            }
                                            else
                                            {
                                                <td></td>
                                            }
                                            @if (!String.IsNullOrEmpty(item.SignaturePath))
                                            {

                                                <td><img src="@item.SignaturePath.Replace("~","")" height="100px" width="100px" /></td>
                                            }
                                            else
                                            {
                                                <td></td>
                                            }


                                        </tr>
                                    }
                                }
                            </table>



                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>